using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace SingleCallQuery.Generator;

/// <summary>
/// Recognises <c>Query.From(..).Where(..).Select(..).ToArray()</c> chains and rewrites the
/// terminal <c>ToArray()</c> call site, via a C# interceptor, into a single fused loop with
/// the lambda *bodies* inlined as ordinary code. No expression tree is compiled or walked.
/// </summary>
[Generator]
public sealed class SingleCallGenerator : IIncrementalGenerator
{
    private const string SourceTypeName = "SingleCallQuery.Demo.Source<T>";

    // Placeholder substituted for each lambda's parameter so we can re-bind it to a fresh
    // carrier variable at emit time without worrying about name collisions across stages.
    private const string Cursor = "__CUR__";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider.CreateSyntaxProvider(
            predicate: static (node, _) =>
                node is InvocationExpressionSyntax
                {
                    Expression: MemberAccessExpressionSyntax { Name.Identifier.ValueText: "ToArray" }
                },
            transform: static (ctx, _) => Analyze(ctx))
            .Where(static c => c is not null)
            .Select(static (c, _) => c!);

        // The compiler binds [InterceptsLocation(..)] by its exact metadata name, so a
        // file-local polyfill won't be recognised. Emit a real one only if the target
        // framework doesn't already ship it (avoids a duplicate-type error when it does).
        var hasAttr = context.CompilationProvider.Select(static (c, _) =>
            c.GetTypeByMetadataName("System.Runtime.CompilerServices.InterceptsLocationAttribute") is not null);

        context.RegisterSourceOutput(candidates.Collect().Combine(hasAttr),
            static (spc, pair) => Emit(spc, pair.Left, pair.Right));
    }

    private const string PolyfillAttribute = """
        // <auto-generated/>
        namespace System.Runtime.CompilerServices
        {
            [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]
            internal sealed class InterceptsLocationAttribute : global::System.Attribute
            {
                public InterceptsLocationAttribute(int version, string data) { }
            }
        }
        """;

    private sealed record Stage(bool IsWhere, string Body);  // Body uses Cursor for the parameter

    private sealed record Plan(
        string AttributeText, string OrigType, string FinalType, ImmutableArray<Stage> Stages,
        ImmutableArray<string> Usings, string? CallSiteNamespace);

    private static Plan? Analyze(GeneratorSyntaxContext ctx)
    {
        var model = ctx.SemanticModel;
        var toArray = (InvocationExpressionSyntax)ctx.Node;

        if (model.GetSymbolInfo(toArray).Symbol is not IMethodSymbol toArraySym) return null;
        if (!IsSource(toArraySym.ContainingType)) return null;

        var receiver = ((MemberAccessExpressionSyntax)toArray.Expression).Expression;

        // Final element type R, from the receiver's Source<R>.
        if (model.GetTypeInfo(receiver).Type is not INamedTypeSymbol finalSource ||
            !IsSource(finalSource) || finalSource.TypeArguments.Length != 1)
            return null;

        // Walk the receiver chain inward, collecting Where/Select stages (outermost first).
        var stages = new List<Stage>();
        var current = receiver;
        while (current is InvocationExpressionSyntax inv &&
               inv.Expression is MemberAccessExpressionSyntax ma &&
               ma.Name.Identifier.ValueText is "Where" or "Select")
        {
            if (model.GetSymbolInfo(inv).Symbol is not IMethodSymbol opSym || !IsSource(opSym.ContainingType))
                return null;
            if (inv.ArgumentList.Arguments.Count != 1 ||
                inv.ArgumentList.Arguments[0].Expression is not LambdaExpressionSyntax lambda)
                return null;

            var param = lambda switch
            {
                SimpleLambdaExpressionSyntax s => s.Parameter.Identifier.ValueText,
                ParenthesizedLambdaExpressionSyntax p when p.ParameterList.Parameters.Count == 1
                    => p.ParameterList.Parameters[0].Identifier.ValueText,
                _ => null,
            };
            if (param is null || lambda.Body is not ExpressionSyntax body) return null;  // expression-bodied only

            var isWhere = ma.Name.Identifier.ValueText == "Where";
            if (!isWhere)
            {
                // Projection must be a nameable type (anonymous types can't appear in a signature).
                if (model.GetTypeInfo(body).Type is not { } t || t.TypeKind == TypeKind.Error || t.IsAnonymousType)
                    return null;
            }

            // Rebind the parameter to our cursor placeholder so stages can be chained safely.
            var rewritten = (new ParamRewriter(param).Visit(body) ?? body).ToString();
            stages.Add(new Stage(isWhere, rewritten));
            current = ma.Expression;
        }
        if (stages.Count == 0) return null;
        stages.Reverse();

        // Original element type T, from the root producer's Source<T>.
        if (model.GetTypeInfo(current).Type is not INamedTypeSymbol rootSource ||
            !IsSource(rootSource) || rootSource.TypeArguments.Length != 1)
            return null;

        var location = model.GetInterceptableLocation(toArray);
        if (location is null) return null;

        var usings = toArray.SyntaxTree.GetCompilationUnitRoot()
            .Usings.Select(u => u.ToString()).ToImmutableArray();
        var ns = model.GetEnclosingSymbol(toArray.SpanStart)?.ContainingNamespace is { IsGlobalNamespace: false } cns
            ? cns.ToDisplayString() : null;

        return new Plan(
            location.GetInterceptsLocationAttributeSyntax(),
            rootSource.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            finalSource.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            stages.ToImmutableArray(), usings, ns);
    }

    private static bool IsSource(INamedTypeSymbol? t) =>
        t is { Name: "Source" } && t.OriginalDefinition.ToDisplayString() == SourceTypeName;

    private static void Emit(SourceProductionContext spc, ImmutableArray<Plan> plans, bool hasAttr)
    {
        if (plans.IsDefaultOrEmpty) return;
        if (!hasAttr) spc.AddSource("InterceptsLocationAttribute.g.cs", PolyfillAttribute);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/> single-call query interceptors");
        sb.AppendLine("#nullable enable");

        var usings = new SortedSet<string>(System.StringComparer.Ordinal);
        foreach (var p in plans)
        {
            foreach (var u in p.Usings) usings.Add(u);
            if (p.CallSiteNamespace is { Length: > 0 } cns) usings.Add($"using {cns};");
        }
        foreach (var u in usings) sb.AppendLine(u);

        sb.AppendLine();
        sb.AppendLine("namespace Generated");
        sb.AppendLine("{");
        sb.AppendLine("    internal static class __SingleCallInterceptors");
        sb.AppendLine("    {");

        for (int i = 0; i < plans.Length; i++)
        {
            var p = plans[i];
            sb.AppendLine($"        {p.AttributeText}");
            sb.AppendLine($"        public static {p.FinalType}[] ToArray_{i}(this global::SingleCallQuery.Demo.Source<{p.FinalType}> __q)");
            sb.AppendLine("        {");
            sb.AppendLine("            global::System.Console.WriteLine(\"[gen     ] single fused pass, zero expression trees compiled\");");
            sb.AppendLine($"            var __out = new global::System.Collections.Generic.List<{p.FinalType}>();");
            sb.AppendLine($"            foreach (var __e in __q.GetRoot<{p.OrigType}>())");
            sb.AppendLine("            {");

            string cur = "__e";
            int s = 0;
            foreach (var stage in p.Stages)
            {
                var body = stage.Body.Replace(Cursor, cur);
                if (stage.IsWhere)
                {
                    sb.AppendLine($"                if (!({body})) continue;");
                }
                else
                {
                    sb.AppendLine($"                var __v{s} = {body};");
                    cur = $"__v{s}";
                    s++;
                }
            }

            sb.AppendLine($"                __out.Add({cur});");
            sb.AppendLine("            }");
            sb.AppendLine("            return __out.ToArray();");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        spc.AddSource("SingleCallInterceptors.g.cs", sb.ToString());
    }

    /// <summary>Replaces references to a lambda parameter with the <see cref="Cursor"/> placeholder.</summary>
    private sealed class ParamRewriter : CSharpSyntaxRewriter
    {
        private readonly string _param;
        public ParamRewriter(string param) => _param = param;

        public override SyntaxNode? VisitIdentifierName(IdentifierNameSyntax node)
            => node.Identifier.ValueText == _param
                ? SyntaxFactory.IdentifierName(Cursor).WithTriviaFrom(node)
                : base.VisitIdentifierName(node);
    }
}
